// @flow

// ------------------------------------
// Code generated by protoc-gen-flow
// source: google/protobuf/timestamp.proto
// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!
// ------------------------------------

declare type Timestamp = {|
	seconds: string;
	nanos: number;
|};
