// @flow

// ------------------------------------
// Code generated by protoc-gen-flow
// source: rdd.proto
// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!
// ------------------------------------

declare type RDDProvisionRequest = {|
	runID: string;
|};

declare type RDDProvisionResponse = {|
	id: string;
|};

declare type RDDStatusRequest = {|
	id: string;
|};

declare type RDDStatusResponse = {|
	state: UNKNONWN TYPE;
	runID: string;
	creationDate: string;
	updateDate: string;
	URL: string;
|};

declare type RDDDeprovisionRequest = {|
	id: string;
|};

declare type RDDDeprovisionResponse = {|
|};

declare type ActionRequest = {|
|};

declare type ActionResponse = {|
	success: boolean;
|};

declare type Resource = {|
	kind: string;
|};
